### ISSUE TITLE
Support for CM19E X10 controller

### ISSUE THREAD

**Issue by mralapete** [genielabs/HomeGenie#343]
The X10 controller CM15Pro has now been discontinued. The only X10 controller now available for sale in Europe is the CM19E, a USB RF only unit. The Vendor ID number for the CM15Pro is 0bc70001 while the Vendor ID number for the CM19E is 0bc70002. The protocol for both units is similar except the CM19E does not include PL (Power Line) control.

Would it be possible to edit the XtenLib to add support for this controller.

**Comment by tuicemen** [comment]
This would also open HG to users of the CM19A (the North American version of the same module)
When the CM15A became back ordered X10WTI shipped the CM19A as a replacement so there are lots of users with this module.

**Comment by genemars** [comment]
I personally do not own a CM19E but I could try extending XTenLib in order to support this device as well.
@mralapete do you have a CM19E to eventually help testing/debugging?

**Comment by tuicemen** [comment]
I wonder if when doing this code could would also allow the cm15 to send RF or can it do that and Im missing something. I CAN test a CM19A

**Comment by mralapete** [comment]
@genemars I do indeed. I have it running on a Raspberry Pi using Mochad. The CM15Pro runs on the same Raspberry Pi by hot swapping the two controllers so if you need any testing done with it in HomeGenie just let me know

**Comment by genemars** [comment]
Ok... good to know you both can help testing. I'll give a peek at XTenLib code soon.

**Comment by genemars** [comment]
Ok.. I've got something to test. Can you guys compile and test `xten-lib-donet` from source?

**Comment by tuicemen** [comment]
I'm  on holidays right now for one more week with no access to my pi. Will be another week before I can test, hope that doesn't  slow development to much

**Comment by mralapete** [comment]
@genemars could you include the link to your revised XTenLib revised source code

**Comment by genemars** [comment]
@mralapete 

https://github.com/genielabs/x10-lib-dotnet/tree/cm19/

Run the **Test.X10** program to test and debug.
I am not sure that the protocol is the same as CM11/CM15 so there might be data decoding errors.

**Comment by mralapete** [comment]
@genemars I've cloned the Github https://github.com/genielabs/x10-lib-dotnet/tree/cm19/ on the Raspberry Pi but cannot compile as there's no makefie present. I'm in the folder x10-lib-dotnet and have used the ./configure, make and sudo make install method but it informs me that no makefile is present

**Comment by genemars** [comment]
compile with visual studio or monodevelop

**Comment by mralapete** [comment]
Yes nuget is required to successfully build with xbuild

Ran Test.CM15.exe with the CM19E attached and here's the output

2018-11-12 14:03:12.3609 XTenLib.Drivers.CM15.Open Error System.Exception: X10 CM15Pro device not connected.
  at XTenLib.Drivers.CM15.Open () [0x00022] in <2fbe82fc52354623bdf4e725fa062f3a>:0

**Comment by mralapete** [comment]
@genemars this is the url for your CM19 branch https://github.com/genielabs/x10-lib-dotnet/tree/cm19 yet this is the url for the clone or download https://github.com/genielabs/x10-lib-dotnet.git

Is that clone or download url for the master or branch

**Comment by genemars** [comment]
@mralapete this is the download link for `cm19` branch:

https://github.com/genielabs/x10-lib-dotnet/archive/cm19.zip

**Comment by mralapete** [comment]
Do you have the git clone url. I'm doing this via a Raspbian terminal straight to the Raspberry Pi

**Comment by genemars** [comment]
Clone as usual then `git checkout cm19` to switch to the proper branch.


Il giorno lun 12 nov 2018, 22:14 mralapete <notifications@github.com> ha
scritto:

**Comment by mralapete** [comment]
Ok got the correct branch and compiled ok.

Ran TestX10.exe and here's the output

2018-11-12 22:39:17.0342 XTenLib.Drivers.CM19.Open Error System.Exception: X10 CM19 device not connected.
  at XTenLib.Drivers.CM19.Open () [0x00022] in <f4e8e8a5b9b34544bdce6ae429ac9398>:0

Tried unplugging and plugging the CM19E and still the same output. It is not connecting.

My CM19E is working fine in Mochad so I know the unit is working

**Comment by genemars** [comment]
can you please do a `lsusb` ?

**Comment by mralapete** [comment]
Contents of lsusb as posted in previous post

Contents of lsusb as follows

Bus 001 Device 004: ID 0bc7:0002 X10 Wireless Technology, Inc. Firecracker Interface (ACPI-compliant)

**Comment by mralapete** [comment]
$ dmesg | tail -n 20
[   31.176275] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   31.176294] brcmfmac: power management disabled
[   31.467085] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   31.467097] Bluetooth: BNEP filters: protocol multicast
[   31.467124] Bluetooth: BNEP socket layer initialized
[   32.992146] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   38.735535] input: lircd-uinput as /devices/virtual/input/input0
[  657.763970] NOHZ: local_softirq_pending 40
[  834.466534] Indeed it is in host mode hprt0 = 00041901
[  834.676420] usb 1-1: new low-speed USB device number 2 using dwc_otg
[  834.677379] Indeed it is in host mode hprt0 = 00041901
[  834.922719] usb 1-1: New USB device found, idVendor=0bc7, idProduct=0002
[  834.922736] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  834.922744] usb 1-1: Product: USB Transceiver
[  834.922753] usb 1-1: Manufacturer: X10 Wireless Technology Inc
[  835.074702] Registered IR keymap rc-ati-x10
[  835.074943] rc rc0: X10 Wireless Technology Inc USB Transceiver as /devices/platform/soc/20980000.usb/usb1/1-1/1-1:1.0/rc/rc0
[  835.075188] input: X10 Wireless Technology Inc USB Transceiver as /devices/platform/soc/20980000.usb/usb1/1-1/1-1:1.0/rc/rc0/input1
[  835.075483] input: X10 Wireless Technology Inc USB Transceiver mouse as /devices/platform/soc/20980000.usb/usb1/1-1/1-1:1.0/input/input2
[  835.083916] usbcore: registered new interface driver ati_remote
pi@raspberrypi:~ $

**Comment by mralapete** [comment]
Ok just did a little searching and came across this. As you suggested there is a conflict with drivers

https://cuddonnet.blogspot.com/2013/02/how-to-disable-interfering-linux-kernel.html

Made the changes suggested and the dmesg output as follows

 usb 1-1: New USB device found, idVendor=0bc7, idProduct=0002
[  418.480942] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  418.480951] usb 1-1: Product: USB Transceiver
[  418.480958] usb 1-1: Manufacturer: X10 Wireless Technology Inc
pi@raspberrypi:~ $

The offending drivers have now been blacklisted and are now no longer loading and everything looks ok.

Ran the TestX10.exe again and the output as follows

2018-11-13 12:37:54.9277 XTenLib.Drivers.CM19.Open Error System.Exception: X10 CM19 device not connected.
  at XTenLib.Drivers.CM19.Open () [0x00022] in <f4e8e8a5b9b34544bdce6ae429ac9398>:0

is there possibly other drivers other than lirc_atiusb and ati_remote thats stopping your test program from connecting to the CM19E

**Comment by mralapete** [comment]
This is the current output of your X10 test program

2018-11-13 13:51:04.2762 XTenLib.Drivers.CM19.Open Error System.Exception: X10 CM19 device not connected.
  at XTenLib.Drivers.CM19.Open () [0x00022] in "<f4e8e8a5b9b34544bdce6ae429ac9398>:0"

**Comment by genemars** [comment]
Ok blacklist is ok. Use `sudo` to run the program.

Il giorno mar 13 nov 2018, 13:46 mralapete <notifications@github.com> ha
scritto:

**Comment by mralapete** [comment]
Yes I did that already. I ran the test program with and without sudo. The output was the same in both cases. It still will not connect with the CM 19E.

I was thinking it might be a permissions issue at one stage. I have verified that the CM19E is still working.

**Comment by mralapete** [comment]
@genemars this might be a useful reference for you https://github.com/amccool/x10-cm19a

**Comment by genemars** [comment]
hi @mralapete the code I've posted is actually recognizing my CM21 USB device. The only difference is the product identifier which is "0005" for CM21 instead of "0002".
As already pointed by you, in order to make it work, I had to blacklist the following modules:
**/etc/modprobe.d/blacklist.conf**
```
blacklist ati_remote
blacklist rc_ati_x10
```
Reboot, then running the test program with `sudo` worked for me.
```
$ mono Test.CM15.exe  # without sudo throws error
XTenLib test program, waiting for connection.
2018-11-14 12:15:06.6676 XTenLib.Drivers.CM19.Open Error System.Exception: X10 CM19 device not connected.
  at XTenLib.Drivers.CM19.Open () [0x00020] in <0bbde8deb979486ca05f840ec3677259>:0 
^C

$ sudo mono Test.CM15.exe
XTenLib test program, waiting for connection.
USB Receiver
Interface connection status True
```
So I really have no clue why it is not working with your CM19.

**Comment by mralapete** [comment]
That looks promising.

Ok. Next question. What Mono version are you using. I’m using 5.4.0

Your GitHub built fine with no errors.

Did you build as root.

Did you modify udev rules to allow a user to access a usb device as you know root ownership can only access usb devices

I cloned your GitHub. I installed Nuget to restore packages. I did cd into the correct folder. I did XBuild (or Msbuild as its known now). I ran the X10 Test program using Mono and sudo Mono. 

Did you do anything differently or did I leave a step out.

**Comment by genemars** [comment]
Did you install **libusb-1.0-0-dev** package?
```
sudo apt-get install libusb-1.0-0-dev
```
this package is installed automatically if you've already installed HG, so I forgot to mention about it.

**Comment by mralapete** [comment]
This is a kernel driver. Did you have a look at it https://github.com/amccool/x10-cm19a

**Comment by mralapete** [comment]
Just looking at these instructions to install another driver for the CM19. Note the instructions on chmod and chown. Does your test program require these changes.

Plugin the X10 CM19A transceiver
Grant access to the appropriate USB device to your preferred user account
Execute sudo lsusb to list devices.
Look for a device with the name "X10 Wireless Technology, Inc. Firecracker Interface" and USB ID 0bc7:0002.
Take note of the "Bus" and "Device" IDs.
Execute chmod 600 /dev/bus/usb/<bus ID>/<device ID> to make the device readable and writable by its owner.
Execute chown <user> /dev/bus/usb/<bus ID>/<device ID> to set your preferred user account as the owner of the device.

**Comment by genemars** [comment]
> Take note of the "Bus" and "Device" IDs.
> Execute chmod 600 /dev/bus/usb// to make the device readable and writable by its owner.

While trying to make CM21 work I've also come across similar solution and performed those *chmod* commands but I don't think that was relevant. What made my CM21 work was the `/etc/modprobe.d/blacklist.conf`.

At this point I think I really need to get hands on the CM19 to try to figure out the issue and make it work. I also believe that CM19 RF data encoding/decoding process might be a little bit different from CM15.
So I just ordered a CM19... it might take a couple of weeks until it gets here.

**Comment by mralapete** [comment]
@genemars
 Mochad might be worth checking out. It handles both the CM15 and CM19 so might provide some clues. I did have a look at this Python driver but I'm not sure how it would perform as its been a few years ago since any work was done on it and it's written around a fairly old version of Python https://github.com/burnsfisher/x10pantilt

Hopefully you'll get your CM19E soon and figure out a working solution for HG. Thanks for your time and effort and hopefully my efforts helped too.

**Comment by tuicemen** [comment]
I've not been able to lay my hands on my CM19A as yet Still trying to catch up on all things here.
I'll do some digging tonight to see if I can find it.

**Comment by tuicemen** [comment]
@genemars  have you received you CM19 yet?
I've been busy working on a HG SD downloadable image to get North American Users hooked on HG and the Pi and I just found my CM19A

**Comment by genemars** [comment]
@tuicemen I received my CM19E today and I already got it working.
Well it's sending X10 RF commands but I'm actually having trouble receiving commands.
Furthermore none of the existing CM19 programs for Linux I've tried worked for receiving but only sending.

Anyway I just realized that CM19 cannot be included as part of XTenLib since the PLC protocol is very different.

So I think I will be writing a C# console program from scratch that you can use to test CM19A, if everything works, then I will write a new specific library and HomeGenie interface driver for CM19.

**Comment by tuicemen** [comment]
Ok I'm ready to test when ever your ready I'll keep my cm19 at the top of my x10 parts bin

**Comment by genemars** [comment]
@tuicemen 

https://github.com/genemars/CM19xTest

it is a very basic console application that will send a **A1 ON** command and then will output any RF command received by the CM19.
If you want to send a different command than **A1 ON** you can edit the source code and use the following file for reference: https://github.com/erikdietrich/Daedalus/blob/master/AutomationService/CM19aProtocol.ini

blacklist the following kernel modules and reboot before running the program:
**/etc/modprobe.d/blacklist.conf**
```
blacklist lirc_atiusb
blacklist ati_remote
```
the program must be run with *sudo*.

**Comment by tuicemen** [comment]
forgive me but I'm very new to using a Pi and not very experienced in Linux so just to confirm I make a file /etc/modprobe.d/blacklist.conf then place "blacklist lirc_atiusb" and "blacklist ati_remote" in it save and reboot?

**Comment by tuicemen** [comment]
Do I have to build CM19xTest if so How?

**Comment by genemars** [comment]
@tuicemen it's same as building XTenLib, like discussed earlier in this thread, using **nuget restore** and  **xbuild**.

**Comment by tuicemen** [comment]
ok remember I'm to this? does nuget need to be installed? (i'm running raspbain Stretch lite) I keep getting  `-bash: nuget: command not found` 
if so how? It sure would be quicker if you just supplied the CM19xTest app already compiled.
HomeGenie  stable is installed already with mono 5.4

**Comment by tuicemen** [comment]
Ok says build successful but don't see the test program even in the bin/Debug folder

**Comment by tuicemen** [comment]
ok reran the build and the exe file is now there

**Comment by tuicemen** [comment]
ok looks like it is seeing RF  How do I test the send?

**Comment by tuicemen** [comment]
Ok figured it out!
it sends A1 as soon as the app starts followed by seeing any RF activity.
works fine here!

**Comment by genemars** [comment]
@tuicemen that's awesome. Would you please paste some output so I can ensure that everything is ok and that I can proceed in writing the real driver.

**Comment by tuicemen** [comment]
sure. I'll reconnect and collect some info or does it save a log somewhere?
I noticed security RF codes seemed a little short when watching earlier so I'll try to capture some of those events

**Comment by tuicemen** [comment]
```
2018-11-30 13:55:12.2794 CM19xTest.Program.Main Debug FF
2018-11-30 13:55:13.5256 CM19xTest.Program.Main Debug 02-00
2018-11-30 13:55:13.6136 CM19xTest.Program.Main Debug 02-80
2018-11-30 13:55:23.6414 CM19xTest.Program.Main Debug
2018-11-30 13:55:32.2236 CM19xTest.Program.Main Debug 20-60-9F-20-DF
2018-11-30 13:55:32.3253 CM19xTest.Program.Main Debug 20-60-9F-20-DF
2018-11-30 13:55:32.4373 CM19xTest.Program.Main Debug 20-60-9F-20-DF
2018-11-30 13:55:32.5414 CM19xTest.Program.Main Debug 20-60-9F-20-DF
2018-11-30 13:55:32.6453 CM19xTest.Program.Main Debug 20-60-9F-20-DF
2018-11-30 13:55:32.7573 CM19xTest.Program.Main Debug 20-60-9F-20-DF
2018-11-30 13:55:42.7618 CM19xTest.Program.Main Debug
2018-11-30 13:55:52.7699 CM19xTest.Program.Main Debug
2018-11-30 13:56:01.0932 CM19xTest.Program.Main Debug 02-C0
2018-11-30 13:56:01.2052 CM19xTest.Program.Main Debug 02-C0
2018-11-30 13:56:10.8452 CM19xTest.Program.Main Debug 02-40
2018-11-30 13:56:10.8535 CM19xTest.Program.Main Debug 02-00
2018-11-30 13:56:10.9732 CM19xTest.Program.Main Debug 02-00
2018-11-30 13:56:11.0692 CM19xTest.Program.Main Debug 02-80
2018-11-30 13:56:18.5174 CM19xTest.Program.Main Debug 20-60-9F-08-F7
2018-11-30 13:56:18.8376 CM19xTest.Program.Main Debug 20-60-9F-08-F7
2018-11-30 13:56:18.9494 CM19xTest.Program.Main Debug 20-60-9F-08-F7
2018-11-30 13:56:19.0534 CM19xTest.Program.Main Debug 20-60-9F-08-F7
2018-11-30 13:56:24.4934 CM19xTest.Program.Main Debug 02-C0
2018-11-30 13:56:24.5175 CM19xTest.Program.Main Debug 02-00
2018-11-30 13:56:24.6454 CM19xTest.Program.Main Debug 02-40
2018-11-30 13:56:31.8375 CM19xTest.Program.Main Debug 20-60-9F-18-E7
2018-11-30 13:56:31.9414 CM19xTest.Program.Main Debug 20-60-9F-18-E7
2018-11-30 13:56:32.0534 CM19xTest.Program.Main Debug 20-60-9F-18-E7
2018-11-30 13:56:32.1575 CM19xTest.Program.Main Debug 20-60-9F-18-E7
2018-11-30 13:56:32.2614 CM19xTest.Program.Main Debug 20-60-9F-18-E7
2018-11-30 13:56:32.3734 CM19xTest.Program.Main Debug 20-60-9F-18-E7
2018-11-30 13:56:36.4214 CM19xTest.Program.Main Debug 20-60-9F-38-C7
2018-11-30 13:56:36.5334 CM19xTest.Program.Main Debug 20-60-9F-38-C7
2018-11-30 13:56:36.6374 CM19xTest.Program.Main Debug 20-60-9F-38-C7
2018-11-30 13:56:36.7494 CM19xTest.Program.Main Debug 20-60-9F-38-C7
2018-11-30 13:56:36.8534 CM19xTest.Program.Main Debug 20-60-9F-38-C7
2018-11-30 13:56:36.9575 CM19xTest.Program.Main Debug 20-60-9F-38-C7
2018-11-30 13:56:46.9626 CM19xTest.Program.Main Debug
2018-11-30 13:56:56.9676 CM19xTest.Program.Main Debug
2018-11-30 13:57:06.9726 CM19xTest.Program.Main Debug
2018-11-30 13:57:16.9777 CM19xTest.Program.Main Debug
2018-11-30 13:57:26.9828 CM19xTest.Program.Main Debug
```
this shows the start commands followed by a1 off  then a2 on then off then a3 on&off then A4 on&off
I had thought it seen security commands earlier but the door window modules I activated didn't register.
the last 5 events are heart beats I assume

**Comment by tuicemen** [comment]
if there is a specific signal you'd like me to try just let me know and I'll attempt it.

**Comment by tuicemen** [comment]
Ok same links?

**Comment by tuicemen** [comment]
Ok it appears to see all house codes on/off and the dim brighten commands but no security sensors or security remote signals. here are codes for p1 on followed by dim then brighten just after starting.
```
pi@X10Hub:~/CM19xTest-master/CM19xTest/bin/Debug $ sudo mono CM19xTest.exe
USB Transceiver
2018-11-30 14:50:07.0026 XTenLib.Drivers.CM19.WriteData Debug WriteData: 20-34-CB-58-A7
2018-11-30 14:50:07.7384 XTenLib.Drivers.CM19.WriteData Debug WriteData: 80-01-00-20-14
2018-11-30 14:50:08.2196 XTenLib.Drivers.CM19.WriteData Debug WriteData: 80-01-00-20-14-24-20-20
2018-11-30 14:50:08.2337 XTenLib.Drivers.CM19.WriteData Debug WriteData: 20-60-9F-00-FF
2018-11-30 14:50:08.2580 XTenLib.Drivers.CM19.ReadData Debug ReadData : FF
2018-11-30 14:50:08.3295 XTenLib.Drivers.CM19.ReadData Debug ReadData : FF
2018-11-30 14:50:30.5937 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-00-FF
2018-11-30 14:50:30.7057 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-00-FF
2018-11-30 14:50:30.8097 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-00-FF
2018-11-30 14:50:30.9137 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-00-FF
2018-11-30 14:50:31.0257 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-00-FF
2018-11-30 14:50:31.1296 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-00-FF
2018-11-30 14:50:36.3779 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-98-67
2018-11-30 14:50:36.4900 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-98-67
2018-11-30 14:50:36.5939 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-98-67
2018-11-30 14:50:36.7059 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-98-67
2018-11-30 14:50:36.8102 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-98-67
2018-11-30 14:50:36.9139 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-98-67
2018-11-30 14:50:40.0339 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-88-77
2018-11-30 14:50:40.1380 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-88-77
2018-11-30 14:50:40.2419 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-88-77
2018-11-30 14:50:40.3539 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-88-77
2018-11-30 14:50:40.4579 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-88-77
2018-11-30 14:50:40.5700 XTenLib.Drivers.CM19.ReadData Debug ReadData : 20-30-CF-88-77
```

**Comment by tuicemen** [comment]
perhaps mralapete can confirm the cm19e is different once he returns from his business trip.

**Comment by genemars** [comment]
@tuicemen can you please update and compile the latest CM19xTest source code?
I made a fix and I was able to receive X10 RF security codes (starting with 29) with my CM19E. Oddly I am still not able to receive standard x10 rf codes (starting with 20).

**Comment by tuicemen** [comment]
OK, it didn't turn on my A1 device at start up but I assume you removed that.
the cm19 does see security door windows and motion sensors```

2018-12-03 06:38:21.9482 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-E5-EA                        -04-FB-4C-80
2018-12-03 06:38:22.0682 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-E5-EA                        -04-FB-4C-80
2018-12-03 06:38:25.5799 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-E5-EA                        -84-7B-4C-80
2018-12-03 06:38:25.7080 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-E5-EA                        -84-7B-4C-80
2018-12-03 06:38:25.8282 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-E5-EA                        -84-7B-4C-80
2018-12-03 06:38:25.9563 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-E5-EA                        -84-7B-4C-80
2018-12-03 06:38:26.0842 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-E5-EA                        -84-7B-4C-80
2018-12-03 06:38:51.3563 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-F1-FE-04-FB-FD-80
2018-12-03 06:38:51.4842 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-F1-FE-04-FB-FD-80
2018-12-03 06:38:51.6202 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-F1-FE-04-FB-FD-80
2018-12-03 06:38:51.7482 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-F1-FE-04-FB-FD-80
2018-12-03 06:38:51.8842 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-F1-FE-04-FB-FD-80
2018-12-03 06:38:52.0123 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-F1-FE-84-7B-FD-80
2018-12-03 06:38:52.1482 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-F1-FE-84-7B-FD-80
2018-12-03 06:38:52.2765 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-F1-FE-84-7B-FD-80
2018-12-03 06:38:52.4122 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-F1-FE-84-7B-FD-80
2018-12-03 06:38:52.5482 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-F1-FE-84-7B-FD-80
2018-12-03 06:38:53.2203 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-01-0E-8C-73-A2-80
2018-12-03 06:38:53.3002 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-01-0E-8C-73-A2-80
2018-12-03 06:38:53.3882 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-01-0E-8C-73-A2-80
2018-12-03 06:38:53.4763 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-01-0E-8C-73-A2-80
2018-12-03 06:38:53.5563 XTenLib.Drivers.CM19.ReadData Debug ReadData : 29-01-0E-8C-73-A2-80
```

**Comment by genemars** [comment]
@tuicemen awesome I almost finished writing the driver. I need a few more tests:

A1 ON, A DIM, A BRIGHT
C7 ON, C DIM, C BRIGHT
P2 ON, P DIM, P BRIGHT

I also found codes for X10 Camera pan/tilt control and I will be adding support for those codes as well (starting with 14).

**Comment by tuicemen** [comment]
I'm  away for a few days but will attempt do do something from here but it mat be the week end before I can test. Is there any chance RF sends can be added to the CM15?
The camera pan n tilt codes I dont expect many use any more with wifi cameras now the norm but I can test those for you as well once you add them.

**Comment by genemars** [comment]
@tuiceman It's ok because I've finally managed to make my CM19 see standard rf codes (20). It turned out that the remote I was using works with CM15 but not with CM19. I am now using a different X10 remote that works. So I don't need any further info.
I'll keep you guys posted with the progress of the CM19 driver.

**Comment by tuicemen** [comment]
Thats great news nice to see it isn't  defective as you originaly thought

**Comment by genemars** [comment]
Early release of the new **CM19Lib**:
https://github.com/genielabs/cm19-lib-dotnet
there is also a **Test.X10** program included.

**Comment by mralapete** [comment]
@genmars Just back in the loop and noticed further activity on this.

I built the driver as per your latest link https://github.com/genielabs/cm19-lib-dotnet but strangely cannot connect to my CM19. Similar messages to the ones I posted above.

I've done the following using a the Raspberry Pi Zero W with a copy of Raspbian Stretch Lite with Mono 5.4 and using the CM19 Euro version with no other hardware connected.

Installed the libusb 
git clone https://github.com/genielabs/cm19-lib-dotnet
nuget restore (all ok)
xbuild (all ok no errors)
blacklisted the conflicting ati drivers
rebooted
Plugged in the CM19 and reporting as X10 wireless transceiver as it should
changed to the /bin folder and ran sudo mono Test.X10.exe

Test.X10.exe reporting that it cannot connect to the CM19

As I mentioned earlier the CM19 is a Euro version, the same model as yours. Strange that @tuicemen manage to connect using a similar platform to me.

I also noticed that there are 11 hidden posts above which I cannot access in the body of this issue.Are they hidden for a reason.


S

**Comment by tuicemen** [comment]
In my tests if you had a cm15 connected you can't just unplug it and plug in the cm19 it will not find the cm19.if I rebooted it would see the cm19

**Comment by genemars** [comment]
@mralapete my CM19 is also the Euro version and it's working fine. You expand the hidden posts if you click on the hidden notice.

**Comment by mralapete** [comment]
@tuicemen the setup I'm using never had a CM15 attached. The CM19 when plugged in is correctly identified as the CM19 as per dmesg output. 

@genmars yes I tried but GitHub is denying me access to those hidden pages.

There's nothing that could possibly be taking control of the CM19 when I plug it in so I have no idea what is causing the non connection of the CM19 when running your Test.X10.exe file

**Comment by mralapete** [comment]
@genemars I can now read the hidden posts so I can follow your progress since my last post. It appears that you have the driver functioning correctly. Could you include it in a beta release of HG so I can fully test it for you. 

Can you include

**Comment by mralapete** [comment]
@genemars I can now access the hidden posts so I can follow your progress on this issue since my last post.

It looks like you have created a functioning driver for the CM19 

Could you include this driver in your next beta version of HG so I can fully test it at my end.

**Comment by genemars** [comment]
@mralapete, yes I'm already working on this. There will be a new HG release before Christmas 🎉

**Comment by genemars** [comment]
So I updated the CM19 driver repository and added two examples/test programs.
I also updated the README.md file with instructions for using the examples programs and the driver itself.

https://github.com/genielabs/cm19-lib-dotnet

Have a look and let me know if there's anything else I should put in the README.md file in order to help users get started with this. Also, please, give me some feedback about the examples programs.
Next I'll be integrating this driver in HomeGenie.

**Comment by tuicemen** [comment]
Did you add support for the pan N Tilt? if so you may wish to add a sample usage for them.
I also see no mention of security codes is the driver capable of sending those?
It will be a few more days before I can give this a test run, I can't wait to give it a test run .

**Comment by genemars** [comment]
> Did you add support for the pan N Tilt? if so you may wish to add a sample usage for them.
> I also see no mention of security codes is the driver capable of sending those?
> It will be a few more days before I can give this a test run, I can't wait to give it a test run .

I will add support for camera commands later. Anyway both camera and security messages can already be received or sent as raw messages using the  method **cm19.SendMessage(<raw_bytes>)**.
I will add some examples to the README.md.

**Comment by mralapete** [comment]
@genemars thanks for that nice piece of work. Nice to see development like this back on track in HG. 

I'll close this issue now that you have a working solution.

**Comment by genemars** [comment]
@tuicemen I added support for camera commands as well.
See the [new CM19Lib documentation](https://github.com/genielabs/cm19-lib-dotnet#cm19-x10-rf-transceiver-library-for-home-automation-net).

**Comment by genemars** [comment]
The driver is now ready but the HomeGenie integration it is not yet there.
So I'll reopen this issue so I can reference and auto-close it as the new HG release is published.

**Comment by tuicemen** [comment]
:( well it doesn't work for me I just couldn't wait to test! 
main issue is now my cm15 doesn't work either

**Comment by genemars** [comment]
@tuicemen It works for me. Both CM19 and CM15. Both on a fresh install and upgrade.
The only thing that is required for CM19 to work is to blacklist the kernel drivers as explained before.
In the next HG release blacklisting will not be needed anymore.

**Comment by genemars** [comment]
@tuiceman this might be a problem related to where **libusb** is installed.
Do the following:
```
$ ls -la /usr/local/bin/homegenie/lib/mig/libusb*
lrwxrwxrwx 1 root root 42 Oct 20 12:07 /usr/local/bin/homegenie/lib/mig/libusb-1.0.so -> /lib/arm-linux-gnueabi/libusb-1.0.so.0.1.0
$ ls -la /lib/arm-linux-gnueabihf/libusb-1.0.so.0.1.0
-rw-r--r-- 1 root root 79752 Jun 22  2014 /lib/arm-linux-gnueabihf/libusb-1.0.so.0.1.0
```
basically you have to check that the symbolic link to the **libusb** library is correct.
In the example above, the link is wrong because the directory **/lib/arm-linux-gnueabi** does not exists in more recent versions of Pi.
If the symbolic link point to a wrong path, try to fix the symbolic link and make it point to the right path location:
```
ln -s /lib/arm-linux-gnueabihf/libusb-1.0.so.0.1.0 /usr/local/bin/homegenie/lib/mig/libusb-1.0.so
```

**Comment by genemars** [comment]
@tuicemen I've fixed the **MIG.HomeAutomation.dll** library, so instead of the instructions in my previous messages, just replace the **.dll** file in the **/usr/local/bin/homegenie/lib/mig** folder.
The new **.dll** will take care of creating the needed symbolic links for *libusb* and also removing the kernel drivers for *CM19*.

[MIG.HomeAutomation.zip](https://github.com/genielabs/HomeGenie/files/2662552/MIG.HomeAutomation.zip)

**Comment by tuicemen** [comment]
@genemars ok this was on a fresh install of Raspbian lite with mono 5.4 and HG 1.2-satble then updated to the beta so files were not blacklisted.
 I'll replace the dll and do the black list thing and report back.

**Comment by mralapete** [comment]
@genemars just to confirm I downloaded and installed the beta version .17 and CM19 not working here. I dropped in that dll replacement fie as advised and the X10 icon is still greyed out on the screen. Maybe a little more info on what your current test rig is for this hardware/software wise might help.

**Comment by tuicemen** [comment]
Still not working for me here either just notice the X10 icon at top is greyed out here too.
Also my HomeGenie folder is in /home/pi/ so the location of the dll is /home/pi/homegenie/lib/mig which may also be playing a roll in this not working.

**Comment by tuicemen** [comment]
I downloaded the zip file to my PC opened it then stopped the HG service then using Filezila copied the file to the correct location never changed any permissions.  Humm I just though of something. Windows blocks some aspects of downloaded files and can prevent them from working correctly if not unblocked before unzipping and I didn't do that so I'll retry things. and get back with results.

**Comment by genemars** [comment]
is there any version of homegenie that works for you? start with that and I
will tell you what files to copy from the latest .tgz . This way we can
spot from what dll is the issue coming from.


Il giorno lun 10 dic 2018, 15:25 mralapete <notifications@github.com> ha
scritto:

**Comment by genemars** [comment]
@tuicemen @mralapete I am succesfully running latest HG both on Raspbian and Ubuntu:
**RASPBERRY PI**
```
$ uname -a
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
$ mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-10)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```
**UBUNTU 18**
```
$ uname -a
Linux mobi-dev 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ mono --version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

@tuicemen why are you using mono 5.x and why not installing using **gdebi** and the **.deb** package?
@mralapete are you also trying a "custom" installation as @tuicemen ?

**Comment by tuicemen** [comment]
ok retried with out success both cm15 and 19 don't work .
here is the out put from ls-l
pi@X10Hub:~/homegenie/lib/mig $ ls -l
total 3240
-rw-r--r-- 1 root root   22528 Dec  9 20:12 CM19Lib.dll
lrwxrwxrwx 1 root root      44 Dec 10 09:55 libusb-1.0.so -> /lib/arm-linux-gnueabihf/libusb-1.0.so.0.1.0
-rw-r--r-- 1 root root    6144 Dec  9 20:12 LibUsb.Common.dll
-rw-r--r-- 1 pi   pi    150016 Sep 22 10:59 LibUsbDotNet.dll
-rw-r--r-- 1 root root  158208 Dec  9 20:12 LibUsbDotNet.LibUsbDotNet.dll
-rw-r--r-- 1 root root     163 Dec  3 16:11 lircconfig.xml
-rw-r--r-- 1 root root  295322 Dec  3 16:11 lircremotes.xml
-rwxr-xr-x 1 pi   pi     13312 Sep 22 10:59 MIG.Controllers.dll
-rw-r--r-- 1 pi   pi     49664 Dec 10 09:54 MIG.HomeAutomation.dll
-rwxr-xr-x 1 pi   pi      9728 Sep 22 10:59 MIG.Media.dll
-rw-r--r-- 1 root root   31232 Dec  9 20:13 MIG.Protocols.dll
-rw-r--r-- 1 root root 2406991 Dec  3 16:11 p1db_custom.xml
drwxr-xr-x 2 pi   pi      4096 Nov 25 18:49 v4l
-rw-r--r-- 1 root root   34816 Dec  9 20:13 XTenLib.dll
-rw-r--r-- 1 root root  103936 Dec  9 20:13 ZWaveLib.dll
pi@X10Hub:~/homegenie/lib/mig $

@genemars I was using v1.1-stable.527 and updated to beta 17

**Comment by genemars** [comment]
@tuicemen I updated from beta 16 to beta 17.
```
pi@raspberrypi:~ $ ls -la /usr/local/bin/homegenie/lib/mig
total 3092
drwxr-xr-x 2 pi   pi      4096 Dec 10 10:01 .
drwxrwxr-x 5 pi   pi      4096 Oct 20 11:27 ..
-rw-r--r-- 1 root root   22528 Dec 10 02:44 CM19Lib.dll
lrwxrwxrwx 1 pi   pi        44 Dec 10 10:01 libusb-1.0.so -> /lib/arm-linux-gnueabihf/libusb-1.0.so.0.1.0
-rw-r--r-- 1 root root    6144 Dec 10 02:45 LibUsb.Common.dll
-rw-r--r-- 1 root root  158208 Dec 10 02:45 LibUsbDotNet.LibUsbDotNet.dll
-rw-r--r-- 1 root root     163 Oct 20 12:23 lircconfig.xml
-rw-r--r-- 1 root root  295322 Oct 20 12:23 lircremotes.xml
-rw-r--r-- 1 root root   49152 Dec 10 02:45 MIG.HomeAutomation.dll
-rw-r--r-- 1 root root   31232 Dec 10 02:45 MIG.Protocols.dll
-rw-r--r-- 1 root root 2406991 Oct 20 12:23 p1db_custom.xml
-rw-r--r-- 1 root root   34816 Dec 10 02:45 XTenLib.dll
-rw-r--r-- 1 root root  103936 Dec 10 02:45 ZWaveLib.dll
-rw-r--r-- 1 root root   28234 Dec 10 02:47 zwavenodes.xml
```
Can you output also the root homegenie folder files? Maybe there are old files that should be deleted.
Especially if those files are **.dll** files that are also present in the **lib/mig** folder.

**Comment by tuicemen** [comment]
@genemars I'll try a new image and use the gdebi and the .deb package.
the reason for the Mono version of 5.x is that's what provided the least problems with other addon programs. like email pictures if I remember correctly.
mralapete and I are creating a HG disk image for X10 users and included that mono version to avoid conflicts we both had. mralapete may have more info on the reason why.

**Comment by genemars** [comment]
I see you have wom3 extra files in the **lib/mig** folder :
```
-rw-r--r-- 1 pi   pi    150016 Sep 22 10:59 LibUsbDotNet.dll
```
pheraps this file has to be deleted?

**Comment by tuicemen** [comment]
here is the output from a dir in HomeGenie folder
```
pi@X10Hub:~/homegenie $ dir
automationgroups.xml          M2Mqtt.Net.dll
certaccept.xml                Microsoft.Dynamic.dll
Common.dll                    Microsoft.Scripting.dll
Common.dll.mdb                Microsoft.Scripting.Metadata.dll
Common.Logging.Core.dll       Microsoft.VisualStudio.CodeCoverage.Shim.dll
Common.Logging.dll            MIG.dll
CommonMark.dll                modules.xml
CREDITS.TXT                   NetClientLib.dll
DEBIAN                        NetClientLib.dll.mdb
DEVELOPERS.TXT                Newtonsoft.Json.dll
groups.xml                    NLog.config
HISTORY.TXT                   NLog.dll
HomeGenie.exe                 programs
HomeGenie.exe.config          programs.xml
HomeGenie.exe.mdb             Raspberry.IO.Components.dll
homegenie_factory_config.zip  Raspberry.IO.Components.dll.config
homegenie_program_import.hgx  Raspberry.IO.dll
homegenie_stats.db            Raspberry.IO.GeneralPurpose.dll
html                          Raspberry.IO.InterIntegratedCircuit.dll
ICSharpCode.SharpZipLib.dll   Raspberry.IO.Interop.dll
installed_packages.json       Raspberry.IO.SerialPeripheralInterface.dll
IronPython.dll                Raspberry.System.dll
IronPython.Modules.dll        README.TXT
IronPython.SQLite.dll         release_info.xml
IronPython.Wpf.dll            scheduler.xml
IronRuby.dll                  SerialPortLib.dll
IronRuby.Libraries.dll        sqlite3.dll
IronRuby.Libraries.Yaml.dll   systemconfig.xml
Jint.dll                      tmp
lib                           Ude.dll
LICENCE.TXT                   UnitsNet.dll
LICENSE_GPLV3.TXT             _update
Linux.dll                     UPnP.dll
Linux.dll.mdb                 websocket-sharp.dll
log

```
I noticed some files also have the wrong permission how do I fix that?

**Comment by genemars** [comment]
@tuicemen glad to see you're creating a ready to use image. A more recent mono version is absolutely not the problem. But missing dependencies might be a problem. That's why **gdebi** might come useful because it will install all required dependencies.
I'd suggest to use a standard HG installation and I might then create a work around for sending emails and attachments that works with older mono versions.

**Comment by tuicemen** [comment]
ok reboot didn't help writing new image now

**Comment by mralapete** [comment]
@genemars I've just noticed you're using Mono 3.2.8 on the Raspberry Pi and you say you've updated your system. From that I'm concluding your actually using the Raspbian Jessie build. Mono 4.6 is the build currently in the Raspbian Stretch repos if I'm not mistaken. I'm using Stretch and Mono 5.4 from the Mono project. I don't think we are singing off the same sheet here.

The only customisation I'm using is Mono 5.4 from the Mono project and the Raspbian Stretch build. This was deployed as security cert issues kept breaking email notification functionality on HG and this was the only way to resolve the issue.

**Comment by tuicemen** [comment]
I updated my loghome off grid place last night the X10 works there with the Cm15 but I can't test a Cm19 till I get back up there after the new years it was running beta16 but if I remember it is on mono 4.6 still play with installing Beta 16 here with mono 4.6 but I suspect it will work. using the gdebi

**Comment by tuicemen** [comment]
ok got it working with the cm15 but response time is very slow.
I'll do some experimenting now.
 @genemars  if you could email me I'd like to get so input from you on the Image were working on
  tuicemen at Hotmail dot com
Alternately you can log into http://forums.x10.com and PM me there.

**Comment by mralapete** [comment]
@genemars ok good news. I did a fresh install using your gdebi package installer. I blacklisted the recommended drivers. CM19 now working and turning lights on/off in beta .17. Just to summarise, I am using Raspbian Stretch Lite, installed HG with gdebi which is using Mono 4.6.2. I made no additional changes by replacing the dll file as you recommended nor did I change any file permissions. Its a straightforward gdebi install and the file blacklisting to get the CM19 working.

**Comment by tuicemen** [comment]
looks like what ever was changed between 1.1-stable.527 and 1.2-beta.2 may be what is causing the issue with X10 using the tar installs and mono 5.x
The gdebi package installer works just fine with Mono 4.6.2 as @mralapete  stated.

**Comment by tuicemen** [comment]
I have the CM19A controlling all my X10 regular modules in beta 17 .
I've tested the tar install of  HG1.1-stable527 with mono 5.x and x10 works with it I removed  that version and tried 1.2-beta.2  it installs fine but X10 doesn't work.

I also tried to use the upgrade function which also updates to 1.2-beta.2 but X10 fails for the CM15.  I don't have a cm11 to see if it affects it. I orginally though the updater may be to blame if original installed with tar but I don't believe this now. Ii still need to do some more testing here too.
I don't believe Gene should be locking HG to a Mono version

**Comment by mralapete** [comment]
@tuicemen Gene never mentioned he had pinned HG to any version of Mono. Others found that it was a solution to operational difficulties they were having with certain programs running in HG. If you look above in a previous reply to me he has Mono version 3.2.8 running on the Raspberry Pi while Mono version 4.6.2 is running on Ubuntu 18. It just depends what particular version of Mono is available in the repos at the time of installation.

The main thing is the CM19 driver is now functioning on the latest beta v .17 as promised. Backward compatability is a completely different matter on a stable version. On going enhancements are usually carried out on beta versions in my experience.

@genemars now that the CM19 driver is finally working in HG can you consider my issue resolved.

**Comment by tuicemen** [comment]
> > Gene never mentioned he had pinned HG to any version of Mono


true not directly, but stating 

> > I'd suggest to use a standard HG installation and I might then create a work around for sending emails and attachments that works with older mono versions.


could lead one to think that.

**Comment by tuicemen** [comment]
@genemars  v1.2-stable.18 installs fine using the deb package and both the cm15 and cm19 can send commands without requiring to blacklist files.
Good Job! A very large X10 community  will enjoy this!

**Comment by tuicemen** [comment]
version stable 18 has been running  for a few hours now and not picked up my security module heart beats
So it is looking like the security side of things needs some tweaking.

**Comment by tuicemen** [comment]
Ok just checked again seems it is seeing security heart beats just reporting different then the cm15.
looks like I have to reconfigure things.
@genemars when I go to add modules to a home screen I see the Cm19 listed as a module is there a reason for that? the cm15 isn't shown At least not in previous builds.

**Comment by tuicemen** [comment]
Ok I got all my security Door window sensors and security key flobs entered.
Although the Cm19 does see security plam pad signals (sh624) it doesn't add them as security modules so you can add them to the HG web page same for security motion sensors

**Comment by genemars** [comment]
@tuicemen Yes the "CM19" module shows the raw RF data. The equivalent for the CM15 is named as "RF".

**Comment by genemars** [comment]
@tuicemen I didn't realize that CM19 is reporting different addresses than CM15.
Would it make sense if I try to make both sending same addresses?

**Comment by tuicemen** [comment]
I believe it is reporting the same address  as the key flobs are the same for both units just the door/window and motion sensors need to be readded.like I say not a big deal as most users won't be swapping controllers. One thing I've noticed is the names don't get saved for the device when the Cm19 sees the module after a reconnect/reboot even though it remembers the module. I believe that is the same for the cm15 to though it use to remember names for the cm15
